/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package beatyourselfwithalog4j;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Scanner;

public class App {
    private static final Logger LOG = LoggerFactory.getLogger(App.class);

    // avoid using LOG except for the string the user enters
    public static void main(String[] args) {
        new Thread(new EchoServer()).start();

        // System.in is a standard input stream
        Scanner sc = new Scanner(System.in);

        System.out.println("Welcome to BeatYourselfWithALog4j2.");

        while (true) {
            System.out.println("What string would you like to beat yourself with?  (Or \"quit\" to quit)");
            String str = sc.nextLine(); // reads string
            if ("quit".equals(str)) {
                System.exit(0);
            }
            System.out.println("Logging your string via Log4j2");
            LOG.info(str);
        }
    }
}
